### ISSUE TITLE
Everything works for me until the last step

### ISSUE THREAD

**Issue by JettyZ** [ahwayakchih/openshift-nodebb#3]
Hi. It's been smooth so far, until this happened:

edge@ubuntu:~/Desktop/nodebb$ git push origin master
Username for 'https://github.com': JettyZ
Password for 'https://JettyZ@github.com': 
remote: Permission to NodeBB/NodeBB.git denied to JettyZ.
fatal: unable to access 'https://github.com/NodeBB/NodeBB.git/': The requested URL returned error: 403

How can I fix this? 

EDIT: I just followed the official documentation and it worked smoothly. (No git involved)

**Comment by ahwayakchih** [comment]
Hi,

It looks like "origin" repo is, for some reason, pointing to the NodeBB repo, instead of Your OpenShift account/site repo.
If you open `~/Desktop/nodebb/.git/config` in text editor, you should have at least three "remotes" defined there:
1. `[remote "origin"]` should have `url` value pointing to address in `yourapp-rhcloud.com` domain
2. `[remote "upstream"]` should have `url` value pointing to NodeBB repo (`https://github.com/NodeBB/NodeBB.git`)
3. `[remote "openshift"]` should have `url` value pointing to this repo (`https://github.com/ahwayakchih/openshift-nodebb.git`)

**Comment by JettyZ** [comment]
Thanks for the response!

**Comment by ahwayakchih** [comment]
Could you check that for me and confirm? It would help a lot if we could find out what went wrong :).
