### ISSUE TITLE
How to access log ?

### ISSUE THREAD

**Issue by Benderwan** [ahwayakchih/openshift-nodebb#9]
Hi there !

I would like to know how to access the nodebb log, as it is not showing up in the openshift log dir nor in the ACP of nodebb. 

Thank you very much !

**Comment by ahwayakchih** [comment]
Hi.

I'm not sure why nodebb does not output anything to `logs/output.log` (file is not even created here).
What's more is that `logs` should be a symlink to a data directory, but isn't.... i'll try to find out why, when i have some free time.

You can check node.js logs at `app-root/logs/nodejs.log`, after logging on to OpenShift command line:

```
cd nodebb
rhc ssh
cat app-root/logs/nodejs.log
```

**Comment by ahwayakchih** [comment]
I tried some changes, but did not commit them yet. It would be great if you could test them (worked for me).
1. Modify `package.json` of NodeBB, so instead of:

```
  "scripts": {
    "start": "node loader.js",
    "test": "mocha ./tests -t 10000"
  },
```

there is:

```
  "scripts": {
    "start": "./nodebb start",
    "test": "mocha ./tests -t 10000"
  },
```
1. Add empty `nodebb/.openshift/marks/use_npm` file

You can make those changes directly on OpenShift server, to prevent unnecessary commits while just testing. In which case:

```
cd nodebb
rhc ssh
touch app-root/repo/.openshift/markers/use_npm
sed -i 's/node loader.js/.\/nodebb start/g' app-root/repo/package.json
exit
rhc app restart
```

**WARNING:** that will stop OpenShift from running NodeBB through supervisor. It will run it directly, just like you would run it locally using `npm start -d` command. On the other hand it will allow you to restart forum from NodeBB's ACP and view logs there.

**Comment by Benderwan** [comment]
Yup, it fixed the issue, and my forum still automatically restart when encountering the issue so no problems adding this fix to core module IMO :smile:

**Comment by ahwayakchih** [comment]
Thanks :).
